spring:
  cloud:
    config:
      uri:
      - http://localhost:8888
  application:
    name: api-ms
server:
  port: 8081


zuul:  routes:    startpage:
     path: /**
     url: http://localhost:8080
    TIMESHEET-MS:
     path: /api/**
    CLIENTS-MS:
     path: /api/**
    PROJECTS-MS:
     path: /api/**
    PHASES-MS:
     path: /api/** 
     
     
---     
zuul:
 sensitiveHeaders:
 ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin     